version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-MAADB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MAABackendDB
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: backend
    container_name: MAAbackend
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    privileged: true
    user: root
    network_mode: host
    command: ["./bin/MAAbackend"]