version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MAABackendDB
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - MAA-backend
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cfg:/root/DailyTaskForMAA/cfg
    privileged: true
    user: root
    # network_mode: host
    networks:
      - MAA-backend
    command: ["sh", "-c", "sleep 20 && ./bin/MAAbackend"]
    restart: on-failure

networks:
  MAA-backend:
    driver: bridge